# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RestaurantMenuApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RestaurantMenuApp

  target 'RestaurantMenuAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RestaurantMenuAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'SDWebImage'


end
